// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)

using System;
using System.Collections.Generic;

namespace Freya {

	public class CodeGenerator {

		int scope = 0;
		public List<string> content = new List<string>();

		public static string GetInheritdocString( string s ) => $"/// <inheritdoc cref=\"{s}\" />";

		public void AppendLine( string s ) => content.Add( $"{new string( '\t', scope )}{s}" );
		public void Comment( string s ) => AppendLine( $"// {s}" );
		public void Using( string s ) => AppendLine( $"using {s};" );
		public void Summary( string s ) => AppendLine( $"/// <summary>{s}</summary>" );
		public void Inheritdoc( string s ) => AppendLine( GetInheritdocString( s ) );
		public void Param( string param, string desc ) => AppendLine( $"/// <param name=\"{param}\">{desc}</param>" );
		public void LineBreak() => content.Add( "" );

		public void BeginScope( string s, bool includeBrackets = true ) {
			AppendLine( includeBrackets ? $"{s} {{" : s );
			scope++;
		}

		public void EndScope( bool includeBrackets = true ) {
			scope--;
			if( includeBrackets )
				AppendLine( "}" );
		}

		public void AppendHeader() {
			Comment( "by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)" );
			Comment( $"Do not manually edit - this file is generated by {nameof(MathfsCodegen)}.cs" );
			LineBreak();
		}

		public CodeScope BracketScope( string s ) => new CodeScope( this, s, true );
		public CodeScope Scope( string s ) => new CodeScope( this, s, false );
		public RegionScope ScopeRegion( string s ) => new RegionScope( this, s );

		public readonly struct CodeScope : IDisposable {

			readonly CodeGenerator gen;
			readonly bool includeBrackets;

			public CodeScope( CodeGenerator gen, string s, bool includeBrackets = true ) {
				this.gen = gen;
				this.includeBrackets = includeBrackets;
				gen.BeginScope( s, includeBrackets );
			}

			public void Dispose() {
				gen.EndScope( includeBrackets );
			}
		}

		public readonly struct RegionScope : IDisposable {

			readonly CodeGenerator gen;

			public RegionScope( CodeGenerator gen, string s ) {
				this.gen = gen;
				gen.AppendLine( $"#region {s}" );
				gen.LineBreak();
			}

			public void Dispose() {
				gen.LineBreak();
				gen.AppendLine( "#endregion" );
			}
		}
	}

}