// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static V complexConj<V,M,Self>(Self v) where Self : IComplex<V,M> => v.complexConj;
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static M complexMul<V,M,Self>(Self a, V b) where Self : IComplex<V,M> => a.complexMul(b);
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static rat2 complexConj(rat2 v) => v.complexConj;
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static rat2 complexMul(rat2 a, rat2 b) => a.complexMul(b);
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static inth2 complexConj(inth2 v) => v.complexConj;
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static rat2 complexMul(inth2 a, inth2 b) => a.complexMul(b);
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static int2 complexConj(this int2 v) => new(v.x, -v.y);
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static int2 complexMul(this int2 a, int2 b) => new(a.x*b.x-a.y*b.y, a.x*b.y+a.y*b.x);
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static Vector2Int complexConj(this Vector2Int v) => new(v.x, -v.y);
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static Vector2Int complexMul(this Vector2Int a, Vector2Int b) => new(a.x*b.x-a.y*b.y, a.x*b.y+a.y*b.x);
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static float2 complexConj(this float2 v) => new(v.x, -v.y);
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static float2 complexMul(this float2 a, float2 b) => new(a.x*b.x-a.y*b.y, a.x*b.y+a.y*b.x);
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static Vector2 complexConj(this Vector2 v) => new(v.x, -v.y);
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static Vector2 complexMul(this Vector2 a, Vector2 b) => new(a.x*b.x-a.y*b.y, a.x*b.y+a.y*b.x);
		/// <inheritdoc cref="IComplex{V,M}.complexConj" />
		public static double2 complexConj(this double2 v) => new(v.x, -v.y);
		/// <inheritdoc cref="IComplex{V,M}.complexMul" />
		public static double2 complexMul(this double2 a, double2 b) => new(a.x*b.x-a.y*b.y, a.x*b.y+a.y*b.x);
	}
}
