// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static D dot<B,D,Self>(Self a, B b) where Self : IDotProduct<B,D> => a.dot(b);
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static rat dot(rat2 a, int2 b) => a.dot(b);
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static rat dot(rat2 a, rat2 b) => a.dot(b);
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static rat dot(inth2 a, inth2 b) => a.dot(b);
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Int32 dot(this int2 a, int2 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Int32 dot(this Vector2Int a, Vector2Int b) => a.x*b.x+a.y*b.y;
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Int32 dot(this int3 a, int3 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Int32 dot(this Vector3Int a, Vector3Int b) => a.x*b.x+a.y*b.y+a.z*b.z;
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Int32 dot(this int4 a, int4 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Single dot(this float2 a, float2 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Single dot(this Vector2 a, Vector2 b) => a.x*b.x+a.y*b.y;
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Single dot(this float3 a, float3 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Single dot(this Vector3 a, Vector3 b) => a.x*b.x+a.y*b.y+a.z*b.z;
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Single dot(this float4 a, float4 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Single dot(this Vector4 a, Vector4 b) => a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w;
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Double dot(this double2 a, double2 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Double dot(this double3 a, double3 b) => math.dot( a, b );
		/// <inheritdoc cref="IDotProduct{B,D}.dot" />
		public static Double dot(this double4 a, double4 b) => math.dot( a, b );
	}
}
