// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IHalfNumber{F}.times2" />
		public static F times2<F,Self>(Self v) where Self : IHalfNumber<F> => v.times2;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IHalfNumber{F}.times2" />
		public static Int32 times2(inth v) => v.times2;
		/// <inheritdoc cref="IHalfNumber{F}.times2" />
		public static int2 times2(inth2 v) => v.times2;
	}
}
