// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger<Self>(Self v) where Self : INumberBase => v.isInteger;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero<Self>(Self v) where Self : INumberBase => v.isZero;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal<Self>(Self v) where Self : INumberBase => v.isOrthogonal;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(rat v) => v.isInteger;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(rat v) => v.isZero;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(rat v) => v.isOrthogonal;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(rat2 v) => v.isInteger;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(rat2 v) => v.isZero;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(rat2 v) => v.isOrthogonal;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(inth v) => v.isInteger;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(inth v) => v.isZero;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(inth v) => v.isOrthogonal;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(inth2 v) => v.isInteger;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(inth2 v) => v.isZero;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(inth2 v) => v.isOrthogonal;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Int32 v) => true;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Int32 v) => v == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Int32 v) => true;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this int2 v) => true;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this int2 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this int2 v) => (v.abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Vector2Int v) => true;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Vector2Int v) => v.x == 0 && v.y == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Vector2Int v) => (new int2(v.x, v.y).abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this int3 v) => true;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this int3 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this int3 v) => (v.abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Vector3Int v) => true;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Vector3Int v) => v.x == 0 && v.y == 0 && v.z == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Vector3Int v) => (new int3(v.x, v.y, v.z).abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this int4 v) => true;
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this int4 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this int4 v) => (v.abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Single v) => v == MathF.Truncate( v );
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Single v) => v == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Single v) => true;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this float2 v) => v.x.isInteger() && v.y.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this float2 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this float2 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Vector2 v) => v.x.isInteger() && v.y.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Vector2 v) => v.x == 0 && v.y == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Vector2 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this float3 v) => v.x.isInteger() && v.y.isInteger() && v.z.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this float3 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this float3 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Vector3 v) => v.x.isInteger() && v.y.isInteger() && v.z.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Vector3 v) => v.x == 0 && v.y == 0 && v.z == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Vector3 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this float4 v) => v.x.isInteger() && v.y.isInteger() && v.z.isInteger() && v.w.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this float4 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this float4 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Vector4 v) => v.x.isInteger() && v.y.isInteger() && v.z.isInteger() && v.w.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Vector4 v) => v.x == 0 && v.y == 0 && v.z == 0 && v.w == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Vector4 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this Double v) => v == Math.Truncate( v );
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this Double v) => v == 0;
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this Double v) => true;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this double2 v) => v.x.isInteger() && v.y.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this double2 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this double2 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this double3 v) => v.x.isInteger() && v.y.isInteger() && v.z.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this double3 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this double3 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
		/// <inheritdoc cref="INumberBase.isInteger" />
		public static Boolean isInteger(this double4 v) => v.x.isInteger() && v.y.isInteger() && v.z.isInteger() && v.w.isInteger();
		/// <inheritdoc cref="INumberBase.isZero" />
		public static Boolean isZero(this double4 v) => math.all( v == 0 );
		/// <inheritdoc cref="INumberBase.isOrthogonal" />
		public static Boolean isOrthogonal(this double4 v) => (v.ceilAwayFrom0().abs() > 0).csum() <= 1;
	}
}
