// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant<Self>(Self v) where Self : IQuadrant2D => v.quadrant;
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant<Self>(Self v) where Self : IQuadrant2D => v.signedQuadrant;
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX<Self>(Self v) where Self : IQuadrant2D => v.quadrantBasisX;
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis<Self>(Self v) where Self : IQuadrant2D => v.quadrantBasis;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant(rat2 v) => v.quadrant;
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant(rat2 v) => v.signedQuadrant;
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX(rat2 v) => v.quadrantBasisX;
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis(rat2 v) => v.quadrantBasis;
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant(inth2 v) => v.quadrant;
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant(inth2 v) => v.signedQuadrant;
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX(inth2 v) => v.quadrantBasisX;
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis(inth2 v) => v.quadrantBasis;
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant(this int2 v) => v.y switch {> 00 when v.x <= 0 => 1,<= 0 when v.x < 00 => 2,< 00 when v.x >= 0 => 3,_ => 0 };
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant(this int2 v) => mathfs.quadrantToSignedQuadrant(v.quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX(this int2 v) => mathfs.quadrantToBasisX(v.quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis(this int2 v) => mathfs.quadrantToBasis(v.quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant(this Vector2Int v) => v.y switch {> 00 when v.x <= 0 => 1,<= 0 when v.x < 00 => 2,< 00 when v.x >= 0 => 3,_ => 0 };
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant(this Vector2Int v) => mathfs.quadrantToSignedQuadrant(v.quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX(this Vector2Int v) => mathfs.quadrantToBasisX(v.quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis(this Vector2Int v) => mathfs.quadrantToBasis(v.quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant(this float2 v) => v.y switch {> 00 when v.x <= 0 => 1,<= 0 when v.x < 00 => 2,< 00 when v.x >= 0 => 3,_ => 0 };
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant(this float2 v) => mathfs.quadrantToSignedQuadrant(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX(this float2 v) => mathfs.quadrantToBasisX(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis(this float2 v) => mathfs.quadrantToBasis(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant(this Vector2 v) => v.y switch {> 00 when v.x <= 0 => 1,<= 0 when v.x < 00 => 2,< 00 when v.x >= 0 => 3,_ => 0 };
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant(this Vector2 v) => mathfs.quadrantToSignedQuadrant(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX(this Vector2 v) => mathfs.quadrantToBasisX(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis(this Vector2 v) => mathfs.quadrantToBasis(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrant" />
		public static Int32 quadrant(this double2 v) => v.y switch {> 00 when v.x <= 0 => 1,<= 0 when v.x < 00 => 2,< 00 when v.x >= 0 => 3,_ => 0 };
		/// <inheritdoc cref="IQuadrant2D.signedQuadrant" />
		public static Int32 signedQuadrant(this double2 v) => mathfs.quadrantToSignedQuadrant(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasisX" />
		public static int2 quadrantBasisX(this double2 v) => mathfs.quadrantToBasisX(v.ceilAwayFrom0().quadrant());
		/// <inheritdoc cref="IQuadrant2D.quadrantBasis" />
		public static (Unity.Mathematics.int2 x,Unity.Mathematics.int2 y) quadrantBasis(this double2 v) => mathfs.quadrantToBasis(v.ceilAwayFrom0().quadrant());
	}
}
