// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static R sign<R,Self>(Self v) where Self : ISignedNumber<R> => v.sign;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static Int32 sign(rat v) => v.sign;
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int2 sign(rat2 v) => v.sign;
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static Int32 sign(inth v) => v.sign;
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int2 sign(inth2 v) => v.sign;
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static Int32 sign(this Int32 v) => Math.Sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int2 sign(this int2 v) => new(v.x.sign(), v.y.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int2 sign(this Vector2Int v) => new(v.x.sign(), v.y.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int3 sign(this int3 v) => new(v.x.sign(), v.y.sign(), v.z.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int3 sign(this Vector3Int v) => new(v.x.sign(), v.y.sign(), v.z.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int4 sign(this int4 v) => new(v.x.sign(), v.y.sign(), v.z.sign(), v.w.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static Int32 sign(this Single v) => Math.Sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int2 sign(this float2 v) => (int2)math.sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int2 sign(this Vector2 v) => new(v.x.sign(), v.y.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int3 sign(this float3 v) => (int3)math.sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int3 sign(this Vector3 v) => new(v.x.sign(), v.y.sign(), v.z.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int4 sign(this float4 v) => (int4)math.sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int4 sign(this Vector4 v) => new(v.x.sign(), v.y.sign(), v.z.sign(), v.w.sign());
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static Int32 sign(this Double v) => Math.Sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int2 sign(this double2 v) => (int2)math.sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int3 sign(this double3 v) => (int3)math.sign(v);
		/// <inheritdoc cref="ISignedNumber{R}.sign" />
		public static int4 sign(this double4 v) => (int4)math.sign(v);
	}
}
