// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static D magSq<D,Self>(Self v) where Self : ISqrMag<D> => v.magSq;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static rat magSq(rat2 v) => v.magSq;
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static rat magSq(inth2 v) => v.magSq;
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Int32 magSq(this int2 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Int32 magSq(this Vector2Int v) => v.x*v.x+v.y*v.y;
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Int32 magSq(this int3 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Int32 magSq(this Vector3Int v) => v.x*v.x+v.y*v.y+v.z*v.z;
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Int32 magSq(this int4 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Single magSq(this float2 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Single magSq(this Vector2 v) => v.x*v.x+v.y*v.y;
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Single magSq(this float3 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Single magSq(this Vector3 v) => v.x*v.x+v.y*v.y+v.z*v.z;
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Single magSq(this float4 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Single magSq(this Vector4 v) => v.x*v.x+v.y*v.y+v.z*v.z+v.w*v.w;
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Double magSq(this double2 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Double magSq(this double3 v) => math.dot( v, v );
		/// <inheritdoc cref="ISqrMag{D}.magSq" />
		public static Double magSq(this double4 v) => math.dot( v, v );
	}
}
