// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static C X<V,C,D,Self>(Self v) where Self : IVec1Base<V,C,D> => v.X;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static V flipX<V,C,D,Self>(Self v) where Self : IVec1Base<V,C,D> => v.flipX;
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static V zeroX<V,C,D,Self>(Self v) where Self : IVec1Base<V,C,D> => v.zeroX;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static rat X(rat2 v) => v.X;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static rat2 flipX(rat2 v) => v.flipX;
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static rat2 zeroX(rat2 v) => v.zeroX;
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static inth X(inth2 v) => v.X;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static inth2 flipX(inth2 v) => v.flipX;
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static inth2 zeroX(inth2 v) => v.zeroX;
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Int32 X(this int2 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static int2 flipX(this int2 v) => new(-v.x, +v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static int2 zeroX(this int2 v) => new(0, v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Int32 X(this Vector2Int v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static Vector2Int flipX(this Vector2Int v) => new(-v.x, +v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static Vector2Int zeroX(this Vector2Int v) => new(0, v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Int32 X(this int3 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static int3 flipX(this int3 v) => new(-v.x, +v.y, +v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static int3 zeroX(this int3 v) => new(0, v.y, v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Int32 X(this Vector3Int v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static Vector3Int flipX(this Vector3Int v) => new(-v.x, +v.y, +v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static Vector3Int zeroX(this Vector3Int v) => new(0, v.y, v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Int32 X(this int4 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static int4 flipX(this int4 v) => new(-v.x, +v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static int4 zeroX(this int4 v) => new(0, v.y, v.z, v.w);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Single X(this float2 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static float2 flipX(this float2 v) => new(-v.x, +v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static float2 zeroX(this float2 v) => new(0, v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Single X(this Vector2 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static Vector2 flipX(this Vector2 v) => new(-v.x, +v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static Vector2 zeroX(this Vector2 v) => new(0, v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Single X(this float3 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static float3 flipX(this float3 v) => new(-v.x, +v.y, +v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static float3 zeroX(this float3 v) => new(0, v.y, v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Single X(this Vector3 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static Vector3 flipX(this Vector3 v) => new(-v.x, +v.y, +v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static Vector3 zeroX(this Vector3 v) => new(0, v.y, v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Single X(this float4 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static float4 flipX(this float4 v) => new(-v.x, +v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static float4 zeroX(this float4 v) => new(0, v.y, v.z, v.w);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Single X(this Vector4 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static Vector4 flipX(this Vector4 v) => new(-v.x, +v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static Vector4 zeroX(this Vector4 v) => new(0, v.y, v.z, v.w);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Double X(this double2 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static double2 flipX(this double2 v) => new(-v.x, +v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static double2 zeroX(this double2 v) => new(0, v.y);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Double X(this double3 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static double3 flipX(this double3 v) => new(-v.x, +v.y, +v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static double3 zeroX(this double3 v) => new(0, v.y, v.z);
		/// <inheritdoc cref="IVec1Base{V,C,D}.X" />
		public static Double X(this double4 v) => v.x;
		/// <inheritdoc cref="IVec1Base{V,C,D}.flipX" />
		public static double4 flipX(this double4 v) => new(-v.x, +v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec1Base{V,C,D}.zeroX" />
		public static double4 zeroX(this double4 v) => new(0, v.y, v.z, v.w);
	}
}
