// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static C Z<V,C,D,Self>(Self v) where Self : IVec3Base<V,C,D> => v.Z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static V flipZ<V,C,D,Self>(Self v) where Self : IVec3Base<V,C,D> => v.flipZ;
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static V zeroZ<V,C,D,Self>(Self v) where Self : IVec3Base<V,C,D> => v.zeroZ;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Int32 Z(this int3 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static int3 flipZ(this int3 v) => new(+v.x, +v.y, -v.z);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static int3 zeroZ(this int3 v) => new(v.x, v.y, 0);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Int32 Z(this Vector3Int v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static Vector3Int flipZ(this Vector3Int v) => new(+v.x, +v.y, -v.z);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static Vector3Int zeroZ(this Vector3Int v) => new(v.x, v.y, 0);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Int32 Z(this int4 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static int4 flipZ(this int4 v) => new(+v.x, +v.y, -v.z, +v.w);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static int4 zeroZ(this int4 v) => new(v.x, v.y, 0, v.w);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Single Z(this float3 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static float3 flipZ(this float3 v) => new(+v.x, +v.y, -v.z);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static float3 zeroZ(this float3 v) => new(v.x, v.y, 0);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Single Z(this Vector3 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static Vector3 flipZ(this Vector3 v) => new(+v.x, +v.y, -v.z);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static Vector3 zeroZ(this Vector3 v) => new(v.x, v.y, 0);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Single Z(this float4 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static float4 flipZ(this float4 v) => new(+v.x, +v.y, -v.z, +v.w);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static float4 zeroZ(this float4 v) => new(v.x, v.y, 0, v.w);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Single Z(this Vector4 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static Vector4 flipZ(this Vector4 v) => new(+v.x, +v.y, -v.z, +v.w);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static Vector4 zeroZ(this Vector4 v) => new(v.x, v.y, 0, v.w);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Double Z(this double3 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static double3 flipZ(this double3 v) => new(+v.x, +v.y, -v.z);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static double3 zeroZ(this double3 v) => new(v.x, v.y, 0);
		/// <inheritdoc cref="IVec3Base{V,C,D}.Z" />
		public static Double Z(this double4 v) => v.z;
		/// <inheritdoc cref="IVec3Base{V,C,D}.flipZ" />
		public static double4 flipZ(this double4 v) => new(+v.x, +v.y, -v.z, +v.w);
		/// <inheritdoc cref="IVec3Base{V,C,D}.zeroZ" />
		public static double4 zeroZ(this double4 v) => new(v.x, v.y, 0, v.w);
	}
}
