// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static Proj projTValue<V,Proj,Self>(Self v, V n) where Self : IVecProjections<V,Proj> => v.projTValue(n);
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static rat projTValue(rat2 v, rat2 n) => v.projTValue(n);
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static rat projTValue(inth2 v, inth2 n) => v.projTValue(n);
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static rat projTValue(this int2 v, int2 n) => v.dot(n)/n.dot(n);
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static rat projTValue(this Vector2Int v, Vector2Int n) => v.dot(n)/n.dot(n);
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static Single projTValue(this float2 v, float2 n) => v.dot(n)/n.dot(n);
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static Single projTValue(this Vector2 v, Vector2 n) => v.dot(n)/n.dot(n);
		/// <inheritdoc cref="IVecProjections{V,Proj}.projTValue" />
		public static Double projTValue(this double2 v, double2 n) => v.dot(n)/n.dot(n);
	}
}
