// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static C cmin<C,Self>(Self v) where Self : IVecComponents<C> => v.cmin;
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static C cmax<C,Self>(Self v) where Self : IVecComponents<C> => v.cmax;
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static C csum<C,Self>(Self v) where Self : IVecComponents<C> => v.csum;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static rat cmin(rat2 v) => v.cmin;
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static rat cmax(rat2 v) => v.cmax;
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static rat csum(rat2 v) => v.csum;
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static inth cmin(inth2 v) => v.cmin;
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static inth cmax(inth2 v) => v.cmax;
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static inth csum(inth2 v) => v.csum;
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Int32 cmin(this int2 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Int32 cmax(this int2 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Int32 csum(this int2 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Int32 cmin(this Vector2Int v) => v.y.min(v.x);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Int32 cmax(this Vector2Int v) => v.y.max(v.x);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Int32 csum(this Vector2Int v) => v.x+v.y;
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Int32 cmin(this int3 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Int32 cmax(this int3 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Int32 csum(this int3 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Int32 cmin(this Vector3Int v) => v.z.min(v.y.min(v.x));
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Int32 cmax(this Vector3Int v) => v.z.max(v.y.max(v.x));
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Int32 csum(this Vector3Int v) => v.x+v.y+v.z;
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Int32 cmin(this int4 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Int32 cmax(this int4 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Int32 csum(this int4 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Single cmin(this float2 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Single cmax(this float2 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Single csum(this float2 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Single cmin(this Vector2 v) => v.y.min(v.x);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Single cmax(this Vector2 v) => v.y.max(v.x);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Single csum(this Vector2 v) => v.x+v.y;
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Single cmin(this float3 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Single cmax(this float3 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Single csum(this float3 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Single cmin(this Vector3 v) => v.z.min(v.y.min(v.x));
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Single cmax(this Vector3 v) => v.z.max(v.y.max(v.x));
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Single csum(this Vector3 v) => v.x+v.y+v.z;
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Single cmin(this float4 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Single cmax(this float4 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Single csum(this float4 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Single cmin(this Vector4 v) => v.w.min(v.z.min(v.y.min(v.x)));
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Single cmax(this Vector4 v) => v.w.max(v.z.max(v.y.max(v.x)));
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Single csum(this Vector4 v) => v.x+v.y+v.z+v.w;
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Double cmin(this double2 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Double cmax(this double2 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Double csum(this double2 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Double cmin(this double3 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Double cmax(this double3 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Double csum(this double3 v) => math.csum(v);
		/// <inheritdoc cref="IVecComponents{C}.cmin" />
		public static Double cmin(this double4 v) => math.cmin(v);
		/// <inheritdoc cref="IVecComponents{C}.cmax" />
		public static Double cmax(this double4 v) => math.cmax(v);
		/// <inheritdoc cref="IVecComponents{C}.csum" />
		public static Double csum(this double4 v) => math.csum(v);
	}
}
