// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IVec4Base{V,C,D}.W" />
		public static C W<V,C,D,Self>(Self v) where Self : IVec4Base<V,C,D> => v.W;
		/// <inheritdoc cref="IVec4Base{V,C,D}.flipW" />
		public static V flipW<V,C,D,Self>(Self v) where Self : IVec4Base<V,C,D> => v.flipW;
		/// <inheritdoc cref="IVec4Base{V,C,D}.zeroW" />
		public static V zeroW<V,C,D,Self>(Self v) where Self : IVec4Base<V,C,D> => v.zeroW;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IVec4Base{V,C,D}.W" />
		public static Int32 W(this int4 v) => v.w;
		/// <inheritdoc cref="IVec4Base{V,C,D}.flipW" />
		public static int4 flipW(this int4 v) => new(+v.x, +v.y, +v.z, -v.w);
		/// <inheritdoc cref="IVec4Base{V,C,D}.zeroW" />
		public static int4 zeroW(this int4 v) => new(v.x, v.y, v.z, 0);
		/// <inheritdoc cref="IVec4Base{V,C,D}.W" />
		public static Single W(this float4 v) => v.w;
		/// <inheritdoc cref="IVec4Base{V,C,D}.flipW" />
		public static float4 flipW(this float4 v) => new(+v.x, +v.y, +v.z, -v.w);
		/// <inheritdoc cref="IVec4Base{V,C,D}.zeroW" />
		public static float4 zeroW(this float4 v) => new(v.x, v.y, v.z, 0);
		/// <inheritdoc cref="IVec4Base{V,C,D}.W" />
		public static Single W(this Vector4 v) => v.w;
		/// <inheritdoc cref="IVec4Base{V,C,D}.flipW" />
		public static Vector4 flipW(this Vector4 v) => new(+v.x, +v.y, +v.z, -v.w);
		/// <inheritdoc cref="IVec4Base{V,C,D}.zeroW" />
		public static Vector4 zeroW(this Vector4 v) => new(v.x, v.y, v.z, 0);
		/// <inheritdoc cref="IVec4Base{V,C,D}.W" />
		public static Double W(this double4 v) => v.w;
		/// <inheritdoc cref="IVec4Base{V,C,D}.flipW" />
		public static double4 flipW(this double4 v) => new(+v.x, +v.y, +v.z, -v.w);
		/// <inheritdoc cref="IVec4Base{V,C,D}.zeroW" />
		public static double4 zeroW(this double4 v) => new(v.x, v.y, v.z, 0);
	}
}
