// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static C magChebyshev<V,C,D,Self>(Self v) where Self : IVec<V,C,D> => v.magChebyshev;
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static C magTaxicab<V,C,D,Self>(Self v) where Self : IVec<V,C,D> => v.magTaxicab;
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane<V,C,D,Self>(Self v, V planePos, V planeNormal) where Self : IVec<V,C,D> => v.pointSideOfPlane(planePos, planeNormal);
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static rat magChebyshev(rat2 v) => v.magChebyshev;
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static rat magTaxicab(rat2 v) => v.magTaxicab;
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(rat2 v, rat2 planePos, rat2 planeNormal) => v.pointSideOfPlane(planePos, planeNormal);
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static inth magChebyshev(inth2 v) => v.magChebyshev;
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static inth magTaxicab(inth2 v) => v.magTaxicab;
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(inth2 v, inth2 planePos, inth2 planeNormal) => v.pointSideOfPlane(planePos, planeNormal);
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Int32 magChebyshev(this int2 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Int32 magTaxicab(this int2 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this int2 v, int2 planePos, int2 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Int32 magChebyshev(this Vector2Int v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Int32 magTaxicab(this Vector2Int v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this Vector2Int v, Vector2Int planePos, Vector2Int planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Int32 magChebyshev(this int3 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Int32 magTaxicab(this int3 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this int3 v, int3 planePos, int3 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Int32 magChebyshev(this Vector3Int v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Int32 magTaxicab(this Vector3Int v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this Vector3Int v, Vector3Int planePos, Vector3Int planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Int32 magChebyshev(this int4 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Int32 magTaxicab(this int4 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this int4 v, int4 planePos, int4 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Single magChebyshev(this float2 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Single magTaxicab(this float2 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this float2 v, float2 planePos, float2 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Single magChebyshev(this Vector2 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Single magTaxicab(this Vector2 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this Vector2 v, Vector2 planePos, Vector2 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Single magChebyshev(this float3 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Single magTaxicab(this float3 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this float3 v, float3 planePos, float3 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Single magChebyshev(this Vector3 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Single magTaxicab(this Vector3 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this Vector3 v, Vector3 planePos, Vector3 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Single magChebyshev(this float4 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Single magTaxicab(this float4 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this float4 v, float4 planePos, float4 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Single magChebyshev(this Vector4 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Single magTaxicab(this Vector4 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this Vector4 v, Vector4 planePos, Vector4 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Double magChebyshev(this double2 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Double magTaxicab(this double2 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this double2 v, double2 planePos, double2 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Double magChebyshev(this double3 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Double magTaxicab(this double3 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this double3 v, double3 planePos, double3 planeNormal) => (v-planePos).dot(planeNormal).sign();
		/// <inheritdoc cref="IVec{V,C,D}.magChebyshev" />
		public static Double magChebyshev(this double4 v) => v.abs().cmax();
		/// <inheritdoc cref="IVec{V,C,D}.magTaxicab" />
		public static Double magTaxicab(this double4 v) => v.abs().csum();
		/// <inheritdoc cref="IVec{V,C,D}.pointSideOfPlane" />
		public static Int32 pointSideOfPlane(this double4 v, double4 planePos, double4 planeNormal) => (v-planePos).dot(planeNormal).sign();
	}
}
