// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static C Y<V,C,D,Self>(Self v) where Self : IVec2Base<V,C,D> => v.Y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static V flipY<V,C,D,Self>(Self v) where Self : IVec2Base<V,C,D> => v.flipY;
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static V zeroY<V,C,D,Self>(Self v) where Self : IVec2Base<V,C,D> => v.zeroY;
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static rat Y(rat2 v) => v.Y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static rat2 flipY(rat2 v) => v.flipY;
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static rat2 zeroY(rat2 v) => v.zeroY;
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static inth Y(inth2 v) => v.Y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static inth2 flipY(inth2 v) => v.flipY;
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static inth2 zeroY(inth2 v) => v.zeroY;
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Int32 Y(this int2 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static int2 flipY(this int2 v) => new(+v.x, -v.y);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static int2 zeroY(this int2 v) => new(v.x, 0);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Int32 Y(this Vector2Int v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static Vector2Int flipY(this Vector2Int v) => new(+v.x, -v.y);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static Vector2Int zeroY(this Vector2Int v) => new(v.x, 0);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Int32 Y(this int3 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static int3 flipY(this int3 v) => new(+v.x, -v.y, +v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static int3 zeroY(this int3 v) => new(v.x, 0, v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Int32 Y(this Vector3Int v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static Vector3Int flipY(this Vector3Int v) => new(+v.x, -v.y, +v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static Vector3Int zeroY(this Vector3Int v) => new(v.x, 0, v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Int32 Y(this int4 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static int4 flipY(this int4 v) => new(+v.x, -v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static int4 zeroY(this int4 v) => new(v.x, 0, v.z, v.w);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Single Y(this float2 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static float2 flipY(this float2 v) => new(+v.x, -v.y);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static float2 zeroY(this float2 v) => new(v.x, 0);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Single Y(this Vector2 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static Vector2 flipY(this Vector2 v) => new(+v.x, -v.y);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static Vector2 zeroY(this Vector2 v) => new(v.x, 0);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Single Y(this float3 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static float3 flipY(this float3 v) => new(+v.x, -v.y, +v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static float3 zeroY(this float3 v) => new(v.x, 0, v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Single Y(this Vector3 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static Vector3 flipY(this Vector3 v) => new(+v.x, -v.y, +v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static Vector3 zeroY(this Vector3 v) => new(v.x, 0, v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Single Y(this float4 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static float4 flipY(this float4 v) => new(+v.x, -v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static float4 zeroY(this float4 v) => new(v.x, 0, v.z, v.w);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Single Y(this Vector4 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static Vector4 flipY(this Vector4 v) => new(+v.x, -v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static Vector4 zeroY(this Vector4 v) => new(v.x, 0, v.z, v.w);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Double Y(this double2 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static double2 flipY(this double2 v) => new(+v.x, -v.y);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static double2 zeroY(this double2 v) => new(v.x, 0);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Double Y(this double3 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static double3 flipY(this double3 v) => new(+v.x, -v.y, +v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static double3 zeroY(this double3 v) => new(v.x, 0, v.z);
		/// <inheritdoc cref="IVec2Base{V,C,D}.Y" />
		public static Double Y(this double4 v) => v.y;
		/// <inheritdoc cref="IVec2Base{V,C,D}.flipY" />
		public static double4 flipY(this double4 v) => new(+v.x, -v.y, +v.z, +v.w);
		/// <inheritdoc cref="IVec2Base{V,C,D}.zeroY" />
		public static double4 zeroY(this double4 v) => new(v.x, 0, v.z, v.w);
	}
}
