// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using Unity.Mathematics;
using UnityEngine;
namespace Freya {
	public static partial class mathfs_generics {
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static W wedge<V,W,Self>(Self a, V b) where Self : IWedgeProduct<V,W> => a.wedge(b);
	}
	public static partial class mathfs {
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static rat wedge(rat2 a, rat2 b) => a.wedge(b);
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static rat wedge(inth2 a, inth2 b) => a.wedge(b);
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static Int32 wedge(this int2 a, int2 b) => a.x*b.y - a.y*b.x;
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static Int32 wedge(this Vector2Int a, Vector2Int b) => a.x*b.y - a.y*b.x;
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static int3 wedge(this int3 a, int3 b) => new(a.y * b.z - a.z * b.y,a.z * b.x - a.x * b.z,a.x * b.y - a.y * b.x);
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static Vector3Int wedge(this Vector3Int a, Vector3Int b) => new(a.y * b.z - a.z * b.y,a.z * b.x - a.x * b.z,a.x * b.y - a.y * b.x);
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static Single wedge(this float2 a, float2 b) => a.x*b.y - a.y*b.x;
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static Single wedge(this Vector2 a, Vector2 b) => a.x*b.y - a.y*b.x;
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static float3 wedge(this float3 a, float3 b) => new(a.y * b.z - a.z * b.y,a.z * b.x - a.x * b.z,a.x * b.y - a.y * b.x);
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static Vector3 wedge(this Vector3 a, Vector3 b) => new(a.y * b.z - a.z * b.y,a.z * b.x - a.x * b.z,a.x * b.y - a.y * b.x);
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static Double wedge(this double2 a, double2 b) => a.x*b.y - a.y*b.x;
		/// <inheritdoc cref="IWedgeProduct{V,W}.wedge" />
		public static double3 wedge(this double3 a, double3 b) => new(a.y * b.z - a.z * b.y,a.z * b.x - a.x * b.z,a.x * b.y - a.y * b.x);
	}
}
