// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace Freya {

	/// <summary>An optimized uniform 3D Quadratic bézier segment, with 3 control points</summary>
	[Serializable] public struct BezierQuad3D : IParamSplineSegment<Polynomial3D,Vector3Matrix3x1> {

		const MethodImplOptions INLINE = MethodImplOptions.AggressiveInlining;

		[SerializeField] Vector3Matrix3x1 pointMatrix;
		[NonSerialized] Polynomial3D curve;
		[NonSerialized] bool validCoefficients;

		/// <summary>Creates a uniform 3D Quadratic bézier segment, from 3 control points</summary>
		/// <param name="p0">The starting point of the curve</param>
		/// <param name="p1">The middle control point of the curve, sometimes called a tangent point</param>
		/// <param name="p2">The end point of the curve</param>
		public BezierQuad3D( Vector3 p0, Vector3 p1, Vector3 p2 ) : this(new Vector3Matrix3x1(p0, p1, p2)){}
		/// <summary>Creates a uniform 3D Quadratic bézier segment, from 3 control points</summary>
		/// <param name="pointMatrix">The matrix containing the control points of this spline</param>
		public BezierQuad3D( Vector3Matrix3x1 pointMatrix ) => (this.pointMatrix,curve,validCoefficients) = (pointMatrix,default,false);

		public Polynomial3D Curve {
			get {
				if( validCoefficients )
					return curve; // no need to update
				validCoefficients = true;
				return curve = new Polynomial3D(
					P0,
					2*(-P0+P1),
					P0-2*P1+P2
				);
			}
		}
		public Vector3Matrix3x1 PointMatrix {[MethodImpl( INLINE )] get => pointMatrix; [MethodImpl( INLINE )] set => _ = ( pointMatrix = value, validCoefficients = false ); }
		/// <summary>The starting point of the curve</summary>
		public Vector3 P0{ [MethodImpl( INLINE )] get => pointMatrix.m0; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m0 = value, validCoefficients = false ); }
		/// <summary>The middle control point of the curve, sometimes called a tangent point</summary>
		public Vector3 P1{ [MethodImpl( INLINE )] get => pointMatrix.m1; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m1 = value, validCoefficients = false ); }
		/// <summary>The end point of the curve</summary>
		public Vector3 P2{ [MethodImpl( INLINE )] get => pointMatrix.m2; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m2 = value, validCoefficients = false ); }
		/// <summary>Get or set a control point position by index. Valid indices from 0 to 2</summary>
		public Vector3 this[ int i ] {
			get => i switch { 0 => P0, 1 => P1, 2 => P2, _ => throw new ArgumentOutOfRangeException( nameof(i), $"Index has to be in the 0 to 2 range, and I think {i} is outside that range you know" ) };
			set { switch( i ){ case 0: P0 = value; break; case 1: P1 = value; break; case 2: P2 = value; break; default: throw new ArgumentOutOfRangeException( nameof(i), $"Index has to be in the 0 to 2 range, and I think {i} is outside that range you know" ); }}
		}
		public static bool operator ==( BezierQuad3D a, BezierQuad3D b ) => a.pointMatrix == b.pointMatrix;
		public static bool operator !=( BezierQuad3D a, BezierQuad3D b ) => !( a == b );
		public bool Equals( BezierQuad3D other ) => P0.Equals( other.P0 ) && P1.Equals( other.P1 ) && P2.Equals( other.P2 );
		public override bool Equals( object obj ) => obj is BezierQuad3D other && pointMatrix.Equals( other.pointMatrix );
		public override int GetHashCode() => pointMatrix.GetHashCode();
		public override string ToString() => $"({pointMatrix.m0}, {pointMatrix.m1}, {pointMatrix.m2})";

		/// <summary>Returns a linear blend between two bézier curves</summary>
		/// <param name="a">The first spline segment</param>
		/// <param name="b">The second spline segment</param>
		/// <param name="t">A value from 0 to 1 to blend between <c>a</c> and <c>b</c></param>
		public static BezierQuad3D Lerp( BezierQuad3D a, BezierQuad3D b, float t ) =>
			new(
				Vector3.LerpUnclamped( a.P0, b.P0, t ),
				Vector3.LerpUnclamped( a.P1, b.P1, t ),
				Vector3.LerpUnclamped( a.P2, b.P2, t )
			);
		/// <summary>Splits this curve at the given t-value, into two curves that together form the exact same shape</summary>
		/// <param name="t">The t-value to split at</param>
		public (BezierQuad3D pre, BezierQuad3D post) Split( float t ) {
			Vector3 a = new Vector3(
				P0.x + ( P1.x - P0.x ) * t,
				P0.y + ( P1.y - P0.y ) * t,
				P0.z + ( P1.z - P0.z ) * t );
			Vector3 b = new Vector3(
				P1.x + ( P2.x - P1.x ) * t,
				P1.y + ( P2.y - P1.y ) * t,
				P1.z + ( P2.z - P1.z ) * t );
			Vector3 p = new Vector3(
				a.x + ( b.x - a.x ) * t,
				a.y + ( b.y - a.y ) * t,
				a.z + ( b.z - a.z ) * t );
			return ( new BezierQuad3D( P0, a, p ), new BezierQuad3D( p, b, P2 ) );
		}
	}
}
