// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace Freya {

	/// <summary>An optimized uniform 1D Cubic bézier segment, with 4 control points</summary>
	[Serializable] public struct BezierCubic1D : IParamSplineSegment<Polynomial,Matrix4x1> {

		const MethodImplOptions INLINE = MethodImplOptions.AggressiveInlining;

		[SerializeField] Matrix4x1 pointMatrix;
		[NonSerialized] Polynomial curve;
		[NonSerialized] bool validCoefficients;

		/// <summary>Creates a uniform 1D Cubic bézier segment, from 4 control points</summary>
		/// <param name="p0">The starting point of the curve</param>
		/// <param name="p1">The second control point of the curve, sometimes called the start tangent point</param>
		/// <param name="p2">The third control point of the curve, sometimes called the end tangent point</param>
		/// <param name="p3">The end point of the curve</param>
		public BezierCubic1D( float p0, float p1, float p2, float p3 ) : this(new Matrix4x1(p0, p1, p2, p3)){}
		/// <summary>Creates a uniform 1D Cubic bézier segment, from 4 control points</summary>
		/// <param name="pointMatrix">The matrix containing the control points of this spline</param>
		public BezierCubic1D( Matrix4x1 pointMatrix ) => (this.pointMatrix,curve,validCoefficients) = (pointMatrix,default,false);

		public Polynomial Curve {
			get {
				if( validCoefficients )
					return curve; // no need to update
				validCoefficients = true;
				return curve = new Polynomial(
					P0,
					3*(-P0+P1),
					3*P0-6*P1+3*P2,
					-P0+3*P1-3*P2+P3
				);
			}
		}
		public Matrix4x1 PointMatrix {[MethodImpl( INLINE )] get => pointMatrix; [MethodImpl( INLINE )] set => _ = ( pointMatrix = value, validCoefficients = false ); }
		/// <summary>The starting point of the curve</summary>
		public float P0{ [MethodImpl( INLINE )] get => pointMatrix.m0; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m0 = value, validCoefficients = false ); }
		/// <summary>The second control point of the curve, sometimes called the start tangent point</summary>
		public float P1{ [MethodImpl( INLINE )] get => pointMatrix.m1; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m1 = value, validCoefficients = false ); }
		/// <summary>The third control point of the curve, sometimes called the end tangent point</summary>
		public float P2{ [MethodImpl( INLINE )] get => pointMatrix.m2; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m2 = value, validCoefficients = false ); }
		/// <summary>The end point of the curve</summary>
		public float P3{ [MethodImpl( INLINE )] get => pointMatrix.m3; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m3 = value, validCoefficients = false ); }
		/// <summary>Get or set a control point position by index. Valid indices from 0 to 3</summary>
		public float this[ int i ] {
			get => i switch { 0 => P0, 1 => P1, 2 => P2, 3 => P3, _ => throw new ArgumentOutOfRangeException( nameof(i), $"Index has to be in the 0 to 3 range, and I think {i} is outside that range you know" ) };
			set { switch( i ){ case 0: P0 = value; break; case 1: P1 = value; break; case 2: P2 = value; break; case 3: P3 = value; break; default: throw new ArgumentOutOfRangeException( nameof(i), $"Index has to be in the 0 to 3 range, and I think {i} is outside that range you know" ); }}
		}
		public static bool operator ==( BezierCubic1D a, BezierCubic1D b ) => a.pointMatrix == b.pointMatrix;
		public static bool operator !=( BezierCubic1D a, BezierCubic1D b ) => !( a == b );
		public bool Equals( BezierCubic1D other ) => P0.Equals( other.P0 ) && P1.Equals( other.P1 ) && P2.Equals( other.P2 ) && P3.Equals( other.P3 );
		public override bool Equals( object obj ) => obj is BezierCubic1D other && pointMatrix.Equals( other.pointMatrix );
		public override int GetHashCode() => pointMatrix.GetHashCode();
		public override string ToString() => $"({pointMatrix.m0}, {pointMatrix.m1}, {pointMatrix.m2}, {pointMatrix.m3})";

		public static explicit operator HermiteCubic1D( BezierCubic1D s ) =>
			new HermiteCubic1D(
				s.P0,
				3*(-s.P0+s.P1),
				s.P3,
				3*(-s.P2+s.P3)
			);
		public static explicit operator CatRomCubic1D( BezierCubic1D s ) =>
			new CatRomCubic1D(
				6*s.P0-6*s.P1+s.P3,
				s.P0,
				s.P3,
				s.P0-6*s.P2+6*s.P3
			);
		public static explicit operator UBSCubic1D( BezierCubic1D s ) =>
			new UBSCubic1D(
				6*s.P0-7*s.P1+2*s.P2,
				2*s.P1-s.P2,
				-s.P1+2*s.P2,
				2*s.P1-7*s.P2+6*s.P3
			);
		/// <summary>Returns a linear blend between two bézier curves</summary>
		/// <param name="a">The first spline segment</param>
		/// <param name="b">The second spline segment</param>
		/// <param name="t">A value from 0 to 1 to blend between <c>a</c> and <c>b</c></param>
		public static BezierCubic1D Lerp( BezierCubic1D a, BezierCubic1D b, float t ) =>
			new(
				Mathfs.Lerp( a.P0, b.P0, t ),
				Mathfs.Lerp( a.P1, b.P1, t ),
				Mathfs.Lerp( a.P2, b.P2, t ),
				Mathfs.Lerp( a.P3, b.P3, t )
			);
		/// <summary>Splits this curve at the given t-value, into two curves that together form the exact same shape</summary>
		/// <param name="t">The t-value to split at</param>
		public (BezierCubic1D pre, BezierCubic1D post) Split( float t ) {
			float a = P0 + ( P1 - P0 ) * t;
			float b = P1 + ( P2 - P1 ) * t;
			float c = P2 + ( P3 - P2 ) * t;
			float d = a + ( b - a ) * t;
			float e = b + ( c - b ) * t;
			float p = d + ( e - d ) * t;
			return ( new BezierCubic1D( P0, a, d, p ), new BezierCubic1D( p, e, c, P3 ) );
		}
	}
}
