// by Freya Holmér (https://github.com/FreyaHolmer/Mathfs)
// Do not manually edit - this file is generated by MathfsCodegen.cs

using System;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace Freya {

	/// <summary>An optimized uniform 3D Cubic hermite segment, with 4 control points</summary>
	[Serializable] public struct HermiteCubic3D : IParamSplineSegment<Polynomial3D,Vector3Matrix4x1> {

		const MethodImplOptions INLINE = MethodImplOptions.AggressiveInlining;

		[SerializeField] Vector3Matrix4x1 pointMatrix;
		[NonSerialized] Polynomial3D curve;
		[NonSerialized] bool validCoefficients;

		/// <summary>Creates a uniform 3D Cubic hermite segment, from 4 control points</summary>
		/// <param name="p0">The starting point of the curve</param>
		/// <param name="v0">The rate of change (velocity) at the start of the curve</param>
		/// <param name="p1">The end point of the curve</param>
		/// <param name="v1">The rate of change (velocity) at the end of the curve</param>
		public HermiteCubic3D( Vector3 p0, Vector3 v0, Vector3 p1, Vector3 v1 ) : this(new Vector3Matrix4x1(p0, v0, p1, v1)){}
		/// <summary>Creates a uniform 3D Cubic hermite segment, from 4 control points</summary>
		/// <param name="pointMatrix">The matrix containing the control points of this spline</param>
		public HermiteCubic3D( Vector3Matrix4x1 pointMatrix ) => (this.pointMatrix,curve,validCoefficients) = (pointMatrix,default,false);

		public Polynomial3D Curve {
			get {
				if( validCoefficients )
					return curve; // no need to update
				validCoefficients = true;
				return curve = new Polynomial3D(
					P0,
					V0,
					-3*P0-2*V0+3*P1-V1,
					2*P0+V0-2*P1+V1
				);
			}
		}
		public Vector3Matrix4x1 PointMatrix {[MethodImpl( INLINE )] get => pointMatrix; [MethodImpl( INLINE )] set => _ = ( pointMatrix = value, validCoefficients = false ); }
		/// <summary>The starting point of the curve</summary>
		public Vector3 P0{ [MethodImpl( INLINE )] get => pointMatrix.m0; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m0 = value, validCoefficients = false ); }
		/// <summary>The rate of change (velocity) at the start of the curve</summary>
		public Vector3 V0{ [MethodImpl( INLINE )] get => pointMatrix.m1; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m1 = value, validCoefficients = false ); }
		/// <summary>The end point of the curve</summary>
		public Vector3 P1{ [MethodImpl( INLINE )] get => pointMatrix.m2; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m2 = value, validCoefficients = false ); }
		/// <summary>The rate of change (velocity) at the end of the curve</summary>
		public Vector3 V1{ [MethodImpl( INLINE )] get => pointMatrix.m3; [MethodImpl( INLINE )] set => _ = ( pointMatrix.m3 = value, validCoefficients = false ); }
		/// <summary>Get or set a control point position by index. Valid indices from 0 to 3</summary>
		public Vector3 this[ int i ] {
			get => i switch { 0 => P0, 1 => V0, 2 => P1, 3 => V1, _ => throw new ArgumentOutOfRangeException( nameof(i), $"Index has to be in the 0 to 3 range, and I think {i} is outside that range you know" ) };
			set { switch( i ){ case 0: P0 = value; break; case 1: V0 = value; break; case 2: P1 = value; break; case 3: V1 = value; break; default: throw new ArgumentOutOfRangeException( nameof(i), $"Index has to be in the 0 to 3 range, and I think {i} is outside that range you know" ); }}
		}
		public static bool operator ==( HermiteCubic3D a, HermiteCubic3D b ) => a.pointMatrix == b.pointMatrix;
		public static bool operator !=( HermiteCubic3D a, HermiteCubic3D b ) => !( a == b );
		public bool Equals( HermiteCubic3D other ) => P0.Equals( other.P0 ) && V0.Equals( other.V0 ) && P1.Equals( other.P1 ) && V1.Equals( other.V1 );
		public override bool Equals( object obj ) => obj is HermiteCubic3D other && pointMatrix.Equals( other.pointMatrix );
		public override int GetHashCode() => pointMatrix.GetHashCode();
		public override string ToString() => $"({pointMatrix.m0}, {pointMatrix.m1}, {pointMatrix.m2}, {pointMatrix.m3})";

		/// <summary>Returns this curve flattened to 2D. Effectively setting z = 0</summary>
		/// <param name="curve3D">The 3D curve to flatten to the Z plane</param>
		public static explicit operator HermiteCubic2D( HermiteCubic3D curve3D ) => new HermiteCubic2D( curve3D.P0, curve3D.V0, curve3D.P1, curve3D.V1 );
		public static explicit operator BezierCubic3D( HermiteCubic3D s ) =>
			new BezierCubic3D(
				s.P0,
				s.P0+(1/3f)*s.V0,
				s.P1-(1/3f)*s.V1,
				s.P1
			);
		public static explicit operator CatRomCubic3D( HermiteCubic3D s ) =>
			new CatRomCubic3D(
				-2*s.V0+s.P1,
				s.P0,
				s.P1,
				s.P0+2*s.V1
			);
		public static explicit operator UBSCubic3D( HermiteCubic3D s ) =>
			new UBSCubic3D(
				-s.P0-(7/3f)*s.V0+2*s.P1-(2/3f)*s.V1,
				2*s.P0+(2/3f)*s.V0-s.P1+(1/3f)*s.V1,
				-s.P0-(1/3f)*s.V0+2*s.P1-(2/3f)*s.V1,
				2*s.P0+(2/3f)*s.V0-s.P1+(7/3f)*s.V1
			);
		/// <summary>Returns a linear blend between two hermite curves</summary>
		/// <param name="a">The first spline segment</param>
		/// <param name="b">The second spline segment</param>
		/// <param name="t">A value from 0 to 1 to blend between <c>a</c> and <c>b</c></param>
		public static HermiteCubic3D Lerp( HermiteCubic3D a, HermiteCubic3D b, float t ) =>
			new(
				Vector3.LerpUnclamped( a.P0, b.P0, t ),
				Vector3.LerpUnclamped( a.V0, b.V0, t ),
				Vector3.LerpUnclamped( a.P1, b.P1, t ),
				Vector3.LerpUnclamped( a.V1, b.V1, t )
			);
	}
}
